//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RM_Messenger.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public System.Guid User_ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public byte[] ProfilePicture { get; set; }
    }
}
