//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RM_Messenger.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RM_Messenger.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string AcceptedStatus {
            get {
                return ResourceManager.GetString("AcceptedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, your account has been successfully created!.
        /// </summary>
        public static string AccountSuccessfullyCreated {
            get {
                return ResourceManager.GetString("AccountSuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RM_Messenger.View.AddContactFirstControl.
        /// </summary>
        public static string AddContactFirstControlPath {
            get {
                return ResourceManager.GetString("AddContactFirstControlPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RM_Messenger.View.AddContactSecondControl.
        /// </summary>
        public static string AddContactSecondControlPath {
            get {
                return ResourceManager.GetString("AddContactSecondControlPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RM_Messenger.View.AddContactThirdControl.
        /// </summary>
        public static string AddContactThirdControlPath {
            get {
                return ResourceManager.GetString("AddContactThirdControlPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Messenger List.
        /// </summary>
        public static string AddContactWindowTitle {
            get {
                return ResourceManager.GetString("AddContactWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add request pending.
        /// </summary>
        public static string AddRequestPendingStatus {
            get {
                return ResourceManager.GetString("AddRequestPendingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RM_Messenger.View.AddToMessengerRequestFirstControl.
        /// </summary>
        public static string AddToMessengerRequestFirstControlPath {
            get {
                return ResourceManager.GetString("AddToMessengerRequestFirstControlPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RM_Messenger.View.AddToMessengerRequestSecondControl.
        /// </summary>
        public static string AddToMessengerRequestSecondControlPath {
            get {
                return ResourceManager.GetString("AddToMessengerRequestSecondControlPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Messenger Request.
        /// </summary>
        public static string AddToMessengerRequestWindowTitle {
            get {
                return ResourceManager.GetString("AddToMessengerRequestWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUZZ!!!.
        /// </summary>
        public static string Buzz {
            get {
                return ResourceManager.GetString("Buzz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RM_Messenger.View.ChangePasswordControl.
        /// </summary>
        public static string ChangePasswordControlPath {
            get {
                return ResourceManager.GetString("ChangePasswordControlPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePasswordControlTitle {
            get {
                return ResourceManager.GetString("ChangePasswordControlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RM_Messenger.View.ChatControl.
        /// </summary>
        public static string ChatControlPath {
            get {
                return ResourceManager.GetString("ChatControlPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RM! Messenger - Chat.
        /// </summary>
        public static string ChatWindowTitle {
            get {
                return ResourceManager.GetString("ChatWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists in your Messenger List and Address Book..
        /// </summary>
        public static string ContactAlreadyExistsMessage {
            get {
                return ResourceManager.GetString("ContactAlreadyExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not exist. Make sure you have typed the correct Messenger ID or address..
        /// </summary>
        public static string ContactDoesNotExistsMessage {
            get {
                return ResourceManager.GetString("ContactDoesNotExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been added to your Messenger List and Address Book, pending his or her response to your request..
        /// </summary>
        public static string ContactHasBeenAddedMessage {
            get {
                return ResourceManager.GetString("ContactHasBeenAddedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We received your request to create an RM! ID account.\n\nThe validation code is {0}.\n\nIf it wasn&apos;t you, please disregard this email..
        /// </summary>
        public static string CreateAccountMailBodyMessage {
            get {
                return ResourceManager.GetString("CreateAccountMailBodyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RM_Messenger.View.CreateNewAccountControl.
        /// </summary>
        public static string CreateNewAccountControlPath {
            get {
                return ResourceManager.GetString("CreateNewAccountControlPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RM! Messenger ID - Create new account..
        /// </summary>
        public static string CreateNewAccountMailSubject {
            get {
                return ResourceManager.GetString("CreateNewAccountMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RM_Messenger.View.CreateNewAccountNextControl.
        /// </summary>
        public static string CreateNewAccountNextControl {
            get {
                return ResourceManager.GetString("CreateNewAccountNextControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RM_Messenger.View.CreateNewAccountNextControl.
        /// </summary>
        public static string CreateNewAccountNextControlPath {
            get {
                return ResourceManager.GetString("CreateNewAccountNextControlPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create RM! ID.
        /// </summary>
        public static string CreateNewAccountNextWindowTitle {
            get {
                return ResourceManager.GetString("CreateNewAccountNextWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        public static string CreateNewAccountWindowTitle {
            get {
                return ResourceManager.GetString("CreateNewAccountWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declined.
        /// </summary>
        public static string DeclinedStatus {
            get {
                return ResourceManager.GetString("DeclinedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RM_Messenger.View.DisplayImageControl.
        /// </summary>
        public static string DisplayImagePath {
            get {
                return ResourceManager.GetString("DisplayImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Image.
        /// </summary>
        public static string DisplayImageTitle {
            get {
                return ResourceManager.GetString("DisplayImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RM_Messenger.View.EmailConfirmationCodeControl.
        /// </summary>
        public static string EmailConfirmationCodeControlPath {
            get {
                return ResourceManager.GetString("EmailConfirmationCodeControlPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Verification.
        /// </summary>
        public static string EmailConfirmationCodeControlTitle {
            get {
                return ResourceManager.GetString("EmailConfirmationCodeControlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RM_Messenger.View.EmailConfirmationCodeFinishedControl.
        /// </summary>
        public static string EmailConfirmationCodeFinishedControlPath {
            get {
                return ResourceManager.GetString("EmailConfirmationCodeFinishedControlPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account successfully created.
        /// </summary>
        public static string EmailConfirmationCodeFinishedControlTitle {
            get {
                return ResourceManager.GetString("EmailConfirmationCodeFinishedControlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email verification failed. Please make sure the email is correct..
        /// </summary>
        public static string EmailVerificationFailed {
            get {
                return ResourceManager.GetString("EmailVerificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ID cannot be empty..
        /// </summary>
        public static string EmptyIdError {
            get {
                return ResourceManager.GetString("EmptyIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password cannot be empty..
        /// </summary>
        public static string EmptyPasswordError {
            get {
                return ResourceManager.GetString("EmptyPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EncryptedPassword.
        /// </summary>
        public static string EncryptedPassword {
            get {
                return ResourceManager.GetString("EncryptedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RM_Messenger.View.ErrorMessageControl.
        /// </summary>
        public static string ErrorMessageControlPath {
            get {
                return ResourceManager.GetString("ErrorMessageControlPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RM_Messenger.View.ForgotPasswordControl.
        /// </summary>
        public static string ForgotPasswordControlPath {
            get {
                return ResourceManager.GetString("ForgotPasswordControlPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string ForgotPasswordControlTitle {
            get {
                return ResourceManager.GetString("ForgotPasswordControlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string FriendListName {
            get {
                return ResourceManager.GetString("FriendListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RM_Messenger.View.HomepageControl.
        /// </summary>
        public static string HomepageControlPath {
            get {
                return ResourceManager.GetString("HomepageControlPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RM! Messenger.
        /// </summary>
        public static string HomepageWindowTitle {
            get {
                return ResourceManager.GetString("HomepageWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ID is not available..
        /// </summary>
        public static string IDNotAvailableError {
            get {
                return ResourceManager.GetString("IDNotAvailableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID should start with a letter..
        /// </summary>
        public static string IdShouldStartWithALetterError {
            get {
                return ResourceManager.GetString("IdShouldStartWithALetterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ID and password do not match..
        /// </summary>
        public static string IncorrectIDAndPassword {
            get {
                return ResourceManager.GetString("IncorrectIDAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not use this ID..
        /// </summary>
        public static string InvalidIdError {
            get {
                return ResourceManager.GetString("InvalidIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regex.
        /// </summary>
        public static string InvalidRegexError {
            get {
                return ResourceManager.GetString("InvalidRegexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RM_Messenger.View.LoginControl.
        /// </summary>
        public static string LoginControlPath {
            get {
                return ResourceManager.GetString("LoginControlPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RM! Messenger.
        /// </summary>
        public static string LoginWindowTitle {
            get {
                return ResourceManager.GetString("LoginWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No response.
        /// </summary>
        public static string NoResponseStatus {
            get {
                return ResourceManager.GetString("NoResponseStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, your password has been successfully changed!.
        /// </summary>
        public static string PasswordSuccessfullyChanged {
            get {
                return ResourceManager.GetString("PasswordSuccessfullyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent.
        /// </summary>
        public static string RecentListName {
            get {
                return ResourceManager.GetString("RecentListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RememberMyIDPassword.
        /// </summary>
        public static string RememberMyIDPassword {
            get {
                return ResourceManager.GetString("RememberMyIDPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string SavedStatus {
            get {
                return ResourceManager.GetString("SavedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        public static string SentStatus {
            get {
                return ResourceManager.GetString("SentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignInAsInvisible.
        /// </summary>
        public static string SignInAsInvisible {
            get {
                return ResourceManager.GetString("SignInAsInvisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignInAutomatically.
        /// </summary>
        public static string SignInAutomatically {
            get {
                return ResourceManager.GetString("SignInAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign-In Problem.
        /// </summary>
        public static string SignInErrorWindowTitle {
            get {
                return ResourceManager.GetString("SignInErrorWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RM_Messenger.View.SigningInControl.
        /// </summary>
        public static string SigningInControlPath {
            get {
                return ResourceManager.GetString("SigningInControlPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RM! Messenger.
        /// </summary>
        public static string SigningInWindowTitle {
            get {
                return ResourceManager.GetString("SigningInWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text not found.
        /// </summary>
        public static string TextNotFoundError {
            get {
                return ResourceManager.GetString("TextNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\..\Text\text.txt.
        /// </summary>
        public static string TextPath {
            get {
                return ResourceManager.GetString("TextPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThemeColorProperty.
        /// </summary>
        public static string ThemeColorProperty {
            get {
                return ResourceManager.GetString("ThemeColorProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID should have at least 3 characters..
        /// </summary>
        public static string TooShortIdError {
            get {
                return ResourceManager.GetString("TooShortIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should have at least 8 characters..
        /// </summary>
        public static string TooShortPasswordError {
            get {
                return ResourceManager.GetString("TooShortPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter an ID and password..
        /// </summary>
        public static string YouMustEnterAnIDAndPasswordError {
            get {
                return ResourceManager.GetString("YouMustEnterAnIDAndPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ID and password do not match..
        /// </summary>
        public static string YourIDAndPasswordDoNotMatchError {
            get {
                return ResourceManager.GetString("YourIDAndPasswordDoNotMatchError", resourceCulture);
            }
        }
    }
}
